name: helloworld-1
run-name: ${{ github.event.head_commit.message }}
on:
    workflow_dispatch:
        inputs:
            name:
                description: "provide input variable name"
                required: true
                default: "world!,welocme to github actions"
    push:
        branches:
            - main    
            - feature/*
        paths:
            - 'src/**'
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            INPUT_NAME: ${{ github.event.inputs.name || 'world' }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Print GitHub event inputs
              run: |
                echo "GitHub event inputs:"
                echo "Input name: $INPUT_NAME"
                echo '${{ toJson(github.event.inputs || {}) }}'